export default [
    {
        id: 1,
        countrycode: "🌏︎",
        title: "Sound of the Things. Estetica della Mappa Sonora",
        url: "http://www.postmediabooks.it/2016/152aurali/9788874901524.htm",
        type: "Book chapter",
        languages: ["Italiano"],
        location: ["🌏︎"],
        terms: ["Cartography studies"],
        authors: ["Raffaele Pe"],
        collection: "",
        annotation: "",
        year: "2016",
        featured: "no",
        featureImage: "",
        featureDescription: ""
    },
    {
        id: 2,
        countrycode: "🌏︎",
        title: "Rethinking the Power of Maps",
        url: "https://link.springer.com/chapter/10.1007/978-3-319-05341-7_17",
        type: "Book chapter",
        languages: ["English"],
        location: ["🌏︎"],
        terms: ["Cartography studies"],
        authors: ["Stefano Bovio"],
        collection: "",
        annotation: "",
        year: "2014",
        featured: "no",
        featureImage: "",
        featureDescription: ""
    },
    {
        id: 5,
        countrycode: "🌏︎",
        title: "Geographies of Fast Growing Cities",
        url: "https://www.amazon.it/Questo-Metropolitan-Architecture-Antonella-Contin/dp/889160903X",
        type: "Book chapter",
        languages: ["English"],
        location: ["🌏︎"],
        terms: ["Cartography studies"],
        authors: ["Alessandra Sammartino", "Stefano Bovio"],
        collection: "",
        annotation: "",
        year: "2015",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 6,
        countrycode: "🌏︎",
        title: "La Mappa Performativa",
        url: "https://medium.com/@lsnmst/la-mappa-performativa-d43a8b860e9d",
        type: "Article",
        languages: ["Italiano"],
        location: ["🌏︎"],
        terms: ["Cartography studies"],
        authors: null,
        collection: "",
        annotation: "",
        year: "2016",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 7,
        countrycode: "UG",
        title: "West Nile Region, Uganda - Integrated and Multi Scalar Planning",
        url: "https://unhabitat.org/sites/default/files/2020/08/integrated_and_multi-scalar_planning_in_west_nile_region_uganda.pdf",
        type: "Book",
        languages: ["English"],
        location: ["Uganda"],
        terms: ["Urban studies"],
        authors: ["Alessandro Frigerio", "Joy Mutai", "Hazel Kuria"],
        collection: "",
        annotation: "",
        year: "2019",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 8,
        countrycode: "🌏︎",
        title: "Mapping Individual Perceptions in Rural Environment: a Participatory Approach for the Integration of Cultural Ecosystem Services in Territorial Planning",
        url: "https://www.researchgate.net/publication/357749360_Mapping_individual_perceptions_in_rural_environments_a_participatory_approach_for_the_integration_of_Cultural_Ecosystem_Services_in_territorial_planning",
        type: "Article",
        languages: ["English"],
        location: ["🌏︎"],
        terms: ["Urban studies"],
        authors: ["Giacomelli Matteo", "Fulvia Calcagni", "Giulia Tagliente"],
        collection: "",
        annotation: "The formal result of a soulful encounter that took place in the magic of BorgoFuturo festival (Val di Fiastra, Italy).",
        year: "2019",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 9,
        countrycode: "CD",
        title: "Managing Water Scarcity in the Internally Displaced People Camps Located in the Second-tier Towns along the N2 National Highway, DR Congo",
        url: "https://www.alessandromusetta.com/cloud/Managing-water-scarcity-IDPs-Rutshuru-YOUsustain.pdf",
        type: "Article",
        languages: ["English"],
        location: ["DR Congo"],
        terms: ["Call for actions"],
        authors: ["Francois Kamate Kasereka", "Joseph Tsongo", " Jackson Kisangani"],
        collection: "",
        annotation: "",
        year: "2022",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 10,
        countrycode: "🌏︎",
        title: "Metropolitan Cartography",
        url: "https://www.alessandromusetta.com/metrocarto/Lk4YGYmTs4LaMCgV.html",
        type: "Online course",
        languages: ["English"],
        location: ["🌏︎"],
        terms: ["Urban studies", "Cartography studies"],
        authors: ["Antonella Contin"],
        collection: "",
        annotation: "The most consistent academic output I have published",
        year: "2019",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 11,
        countrycode: "CD",
        title: "Fishing Against Odds. Fisherwomen of Lake Kivu Fight Against Social Stigma and Discrimination with Mama Cynthia at the Helm.",
        url: "https://icsfarchives.net/21569/",
        type: "Article",
        languages: ["English"],
        location: ["DR Congo"],
        terms: ["Call for actions", "Body-territory"],
        authors: ["Rosine Nsimiri Hamuli"],
        collection: "",
        annotation: "",
        year: "2024",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 12,
        countrycode: "NG",
        title: "Eco-climate Memory of Yam Production of Izzi People, Southest Nigeria",
        url: null,
        type: "Article",
        languages: ["English"],
        location: ["Nigeria"],
        terms: ["Traditional ecological knowledge"],
        authors: ["Okezie Kelechukwu"],
        collection: "",
        annotation: "",
        year: "2024",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 12,
        countrycode: "🌏︎",
        title: "Sound of Things. Play the Silent Intelligence",
        url: "https://www.alessandromusetta.com/soundofthings/",
        type: "Manifesto",
        languages: ["English"],
        location: ["🌏︎"],
        terms: ["Sound art"],
        authors: ["Stefano Bovio", "Raffaele Pe"],
        collection: "",
        annotation: "",
        year: "2015",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 13,
        countrycode: "UG",
        title: "A Food Security Model for Subsistence Farmers and Fisherfolks of the Albertine Region of Uganda",
        url: "https://docs.google.com/presentation/d/1fquKsck_tr3GPNNOkClED8fFMgA7UZzOFcs7oPUeEOU/edit?slide=id.p#slide=id.p",
        type: "Presentation",
        languages: ["English"],
        location: ["Uganda"],
        terms: ["Food geographies"],
        authors: ["Environmental defenders", "Chan Ku Ber Fur"],
        collection: "",
        annotation: "",
        year: "2020",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 14,
        countrycode: "BR",
        title: "End Religious Intolerance through Environmental Education",
        url: "https://www.alessandromusetta.com/cloud/culto-afro-educacao-ambiental_v02.pdf",
        type: "Workshop",
        languages: ["English", "Português"],
        location: ["Brazil"],
        terms: ["Environmental education", "African + african diaspora religions"],
        authors: null,
        collection: "",
        annotation: "",
        year: "2022",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 15,
        countrycode: "CD",
        title: "Tightening Alliances Between Researchers, Earth and Land Rights Defenders between Amazonia and the Congo Basin",
        url: "https://www.alessandromusetta.com/cloud/alliances-aliancas-alianzas-alliances.pdf",
        type: "Article",
        languages: ["English", "Português", "Espanhol", "Français"],
        location: ["DR Congo", "Brazil", "Colombia", "Ecuador"],
        terms: ["Sud-sud cooperation", "Call for actions"],
        authors: null,
        collection: "",
        annotation: "",
        year: "2023",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 16,
        countrycode: "CD",
        title: "Reveal Complexity : Forest, Congo Basin, Ituri And Haut-Uélé Provinces, Mambasa And Watsa Chiefdom, Okapi Wildlife Reserve, Kibali and Ituri River",
        url: "https://www.alessandromusetta.com/cloud/LSNMST-mapping-empty-forest.pdf",
        type: "Workshop",
        languages: ["English"],
        location: ["DR Congo"],
        terms: ["Cartography studies"],
        authors: null,
        collection: "Mapping the Void",
        annotation: "",
        year: "2023",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 17,
        countrycode: "NE",
        title: "Reveal Complexity : Ténéré Desert, Aïr Mountains, Ighazer Plain, Aïr And Ténéré National Nature Reserve, Kawar Oases",
        url: "https://www.alessandromusetta.com/cloud/LSNMST-mapping-empty-desert.pdf",
        type: "Workshop",
        languages: ["English"],
        location: ["Niger"],
        terms: ["Cartography studies"],
        authors: null,
        collection: "Mapping the Void",
        annotation: "",
        year: "2023",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 18,
        countrycode: "AQ",
        title: "Reveal Complexity : Antarctica, Southern Ocean, Ross Sea, Victoria Land, Transantarctic Mountains, Ross Ice Shelf, Mcmurdo Sound, Terra Nova Bay",
        url: "https://www.alessandromusetta.com/cloud/LSNMST-mapping-empty-antarctica.pdf",
        type: "Workshop",
        languages: ["English"],
        location: ["Antarctica"],
        terms: ["Cartography studies"],
        authors: null,
        collection: "Mapping the Void",
        annotation: "",
        year: "2023",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 19,
        countrycode: "BR",
        title: "A Paisagem Sonora da Floresta do Tinguá",
        url: "https://www.alessandromusetta.com/cloud/LSNMST_paisagem-sonora-floresta-tingua.pdf",
        type: "Workshop",
        languages: ["Português"],
        location: ["Brazil"],
        terms: ["Environmental education"],
        authors: ["Onda Verde"],
        collection: "",
        annotation: "",
        year: "2023",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 20,
        countrycode: "🌏︎",
        title: "Instructions to create an eco-cosmological calendar",
        url: "https://www.alessandromusetta.com/cloud/CALENDARIO_ECOCOSMOLOGICO/CALENDARIO_ECOCOSMOLOGICO.pdf",
        type: "Workshop",
        languages: ["English", "Português", "Espanhol"],
        location: ["🌏︎"],
        terms: ["Traditional ecological knowledge", "Cosmology"],
        authors: null,
        collection: "",
        annotation: "",
        year: "2025",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 32,
        countrycode: "UG",
        title: "Along the shores of the Itaka Lya Mwitanzige. A journey that connects women and rights in the northern Albertine Rift, Uganda",
        url: "https://chiroxiphiacaudata.github.io/the-minute-we-fall-silent/",
        type: "Map",
        languages: ["English"],
        location: ["Uganda"],
        terms: ["Women rights", "Ecofeminism"],
        authors: ["Environmental Defenders"],
        collection: "",
        annotation: "",
        year: "2021",
        featured: "yes",
        featureImage: "/archive/images/shores.jpg",
        featureDescription: "550 km to walk along with the Women Environmental and Human Rights Defenders of the Itaka Lya Mwitanzige (lake Albert), the custodians of a land that the extractive industry is clearing.",
    },
    {
        id: 21,
        countrycode: "BR",
        title: "Mapeamento Participativo Do Lixo no Rio Boa Esperança, Nova Iguaçu",
        url: "https://www.alessandromusetta.com/comunidados/arquivo/Brasil/Rio-Boa-Esperanca-Mapeamento-participativo-do-lixo/mapa/diamundiallimpeza/mutirao-dia-mundial-da-limpeza-onda-verde.html",
        type: "Map",
        languages: ["Português"],
        location: ["Brazil"],
        terms: ["Enviornmental education"],
        authors: ["Giulia Tagliente", "Onda Verde"],
        collection: "Comunidados",
        annotation: "",
        year: "2019",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 22,
        countrycode: "BR",
        title: "Aonde Tem Lixo em Tinguá. Mapeamento Participativo do Lixo",
        url: "https://www.alessandromusetta.com/comunidados/arquivo/Brasil/Comunidade-Tingua-Mapeamento-participativo-do-lixo/anexos/01-codigo/lixo/colegio.html",
        type: "Map",
        languages: ["Português"],
        location: ["Brazil"],
        terms: ["Enviornmental education"],
        authors: ["Giulia Tagliente", "Onda Verde"],
        collection: "Comunidados",
        annotation: "",
        year: "2019",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 23,
        countrycode: "BR",
        title: "Entenda a Relação Geográfica Entre as Áreas de Risco e a Raça/Cor d(x)s Morador(x)s, Rio De Janeiro",
        url: "https://www.alessandromusetta.com/comunidados/arquivo/Brasil/Rela%C3%A7%C3%A3o-geogr%C3%A1fica-entre-as-%C3%A1reas-de-risco-e-a-ra%C3%A7acor-d%28x%29s-morador%28x%29s/mapa/raca-risco/pt.html",
        type: "Map",
        languages: ["Português"],
        location: ["Brazil"],
        terms: ["Ethnic and racial studies"],
        authors: ["Giulia Tagliente"],
        collection: "Comunidados",
        annotation: "",
        year: "2020",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 24,
        countrycode: "BR",
        title: "Participatory Mapping of Cultural Ecosystem Services in the Tinguá Community",
        url: "https://www.alessandromusetta.com/comunidados/arquivo/Brasil/Onda-Verde-Um-centro-de-economia-florestal-pela-Baixada-Fluminense/mapas/ces/en.html",
        type: "Map",
        languages: ["English"],
        location: ["Brazil"],
        terms: ["Environmental education"],
        authors: ["Eugenio della Pia", "Giulia Tagliente", "Onda Verde"],
        collection: "Comunidados",
        annotation: "",
        year: "2020",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 25,
        countrycode: "BR",
        title: "Physical Fragility by Urban Expansion, Rio de Janeiro",
        url: "https://www.alessandromusetta.com/comunidados/arquivo/Brasil/Onda-Verde-Um-centro-de-economia-florestal-pela-Baixada-Fluminense/mapas/urban-growth/en.html",
        type: "Map",
        languages: ["English"],
        location: ["Brazil"],
        terms: ["Urban studies"],
        authors: ["Giulia Tagliente", "Onda Verde"],
        collection: "Comunidados",
        annotation: "",
        year: "2020",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 26,
        countrycode: "BR",
        title: "Onda Verde. Um Centro da Economia Florestal pela Baixada Fluminense",
        url: "https://www.alessandromusetta.com/comunidados/arquivo/Brasil/Onda-Verde-Um-centro-de-economia-florestal-pela-Baixada-Fluminense/01-Onda-Verde-Um-centro-de-economia-florestal-pela-Baixada-Fluminense.pdf",
        type: "Report",
        languages: ["English", "Português"],
        location: ["Brazil"],
        terms: ["Forest resources management"],
        authors: ["Onda Verde"],
        collection: "",
        annotation: "",
        year: "2021",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 27,
        countrycode: "IT",
        title: "Innalzamento mari, danni miliardari. Ecco le mappe che lo provano",
        url: "https://valori.it/innalzamento-mari-danni-miliardari-mappe/",
        type: "Map",
        languages: ["Italiano"],
        location: ["Italy"],
        terms: ["Climate change"],
        authors: ["Massimiliano Lepratti", "Roberto Romano"],
        collection: "",
        annotation: "",
        year: "2020",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 28,
        countrycode: "IT",
        title: "Partecipatory Mapping of the Ecosystem Services of the Vallenzuolo Valley",
        url: "https://www.alessandromusetta.com/comunidados/arquivo/Italia/Borgofuturo-Participatory-mapping-of-ecosystem-services/Mapa/borgofuturo/bf19.html",
        type: "Map",
        languages: ["English"],
        location: ["Italy"],
        terms: ["Environmental education"],
        authors: ["Giulia Tagliente", "Borgofuturo", "Terminalia"],
        collection: "Comunidados",
        annotation: "",
        year: "2019",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 29,
        countrycode: "UG",
        title: "The Albertine Region Tracker",
        url: "https://www.watetezi.org/hrd/tracker.html",
        type: "Map",
        languages: ["English"],
        location: ["Uganda"],
        terms: ["Human Rights"],
        authors: ["Environmental Defenders"],
        collection: "",
        annotation: "",
        year: "2020",
        featured: "no",
        featureImage: "",
        featureDescription: "",
    },
    {
        id: 30,
        countrycode: "CD",
        title: "Blood in the Forest",
        url: "https://archive.org/details/environmental-defenders-blood-in-the-forest-v-01/mode/2up",
        type: "Report",
        languages: ["English"],
        location: ["DR Congo"],
        terms: ["Forest resources management"],
        authors: ["Environmental Defenders"],
        collection: "",
        annotation: "",
        year: "2021",
        featured: "yes",
        featureImage: "/archive/images/blood.jpg",
        featureDescription: "The landscape of the Mambasa and Mongbwalu sectors (Ituri Province, DR Congo) are facing an undergoing a gradual degradation. This study focuses on the process of identifying ecologically fragile areas where to implement forest conservation and restoration projects from a local, not purely biological and participatory perspective.",
    },
    {
        id: 31,
        countrycode: "UG",
        title: "664 Hectares",
        url: "https://watetezi.org/data/maps/forest/bugoma.html",
        type: "Map",
        languages: ["English"],
        location: ["Uganda"],
        terms: ["Land rights conflict"],
        authors: ["Environmental Defenders"],
        collection: "",
        annotation: "",
        year: "2021",
        featured: "yes",
        featureImage: "/archive/images/bugoma-CFR.jpg",
        featureDescription: "Two sugar cane companies have cleared thousands of hectares of forest in the disputed areas of the Bugoma Forest in Uganda. This map shows the extent of the deforestation and the speed at which it has occurred. This map was developed as a tool for forest defenders to gain near real-time knowledge of illegal logging activities.",
    },
    {
        id: 33,
        countrycode: "CD",
        title: "Halting the Ecological Crisis and Ecosystem Collaps of the Congo Basin Edge.",
        url: "https://archive.org/details/halting-the-ecological-crisis-and-ecosystem-collapse-of-the-congo-basin-edge-v-2-compressed",
        type: "Report",
        languages: ["English", "Français"],
        location: ["DR Congo"],
        terms: ["Forest resources management"],
        authors: ["Environmental Defenders"],
        collection: "",
        annotation: "",
        year: "2022",
        featured: "yes",
        featureImage: "./images/defence.jpg",
        featureDescription: "The report investigates the concepts of social, ecological and climate justice by focusing on the Watsa territory of the Haut-Uélé province of the DR Congo, and uses ecofeminism as a model of mutual dependence and its intersectional perspective to build practices and solutions as an alternative to the extractivist model. ",
    },
];